language: python
python:
  - 3.6

branches:
  only:
    - master
    - ft-api

install:
  - pip install -r requirements.txt

env:
  - DB=sqlite

script:
  - python manage.py test api --noinput

after_success:
  - coveralls
